// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// capture //
// ------- //

#define capture_wrap_target 0
#define capture_wrap 5
#define capture_pio_version 0

static const uint16_t capture_program_instructions[] = {
            //     .wrap_target
    0x2091, //  0: wait   1 gpio, 17
    0x2092, //  1: wait   1 gpio, 18
    0x2012, //  2: wait   0 gpio, 18
    0x2092, //  3: wait   1 gpio, 18
    0x4008, //  4: in     pins, 8
    0x2012, //  5: wait   0 gpio, 18
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program capture_program = {
    .instructions = capture_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + capture_wrap_target, offset + capture_wrap);
    return c;
}

static inline void capture_program_init(PIO pio, uint sm, uint offset, uint in_base) {
    pio_sm_config c = capture_program_get_default_config(offset);
    sm_config_set_in_pins(&c, in_base);              // GP8..GP15 (multiple of 8)
    sm_config_set_in_shift(&c, false, true, 8);      // shift left, autopush 8
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);   // 8-deep RX FIFO
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

