// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// capture //
// ------- //

#define capture_wrap_target 0
#define capture_wrap 5
#define capture_pio_version 0

static const uint16_t capture_program_instructions[] = {
            //     .wrap_target
    0x2091, //  0: wait   1 gpio, 17
    0x2092, //  1: wait   1 gpio, 18
    0x2012, //  2: wait   0 gpio, 18
    0x2092, //  3: wait   1 gpio, 18
    0x4008, //  4: in     pins, 8
    0x2012, //  5: wait   0 gpio, 18
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program capture_program = {
    .instructions = capture_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = capture_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config capture_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + capture_wrap_target, offset + capture_wrap);
    return c;
}
#endif

// ---------------- //
// capture_per_pclk //
// ---------------- //

#define capture_per_pclk_wrap_target 0
#define capture_per_pclk_wrap 3
#define capture_per_pclk_pio_version 0

static const uint16_t capture_per_pclk_program_instructions[] = {
            //     .wrap_target
    0x2091, //  0: wait   1 gpio, 17
    0x2092, //  1: wait   1 gpio, 18
    0x4008, //  2: in     pins, 8
    0x2012, //  3: wait   0 gpio, 18
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program capture_per_pclk_program = {
    .instructions = capture_per_pclk_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = capture_per_pclk_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config capture_per_pclk_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + capture_per_pclk_wrap_target, offset + capture_per_pclk_wrap);
    return c;
}
#endif

// ---------- //
// pclk_count //
// ---------- //

#define pclk_count_wrap_target 1
#define pclk_count_wrap 5
#define pclk_count_pio_version 0

static const uint16_t pclk_count_program_instructions[] = {
    0x2011, //  0: wait   0 gpio, 17
            //     .wrap_target
    0x2091, //  1: wait   1 gpio, 17
    0xa02b, //  2: mov    x, ~null
    0x00c6, //  3: jmp    pin, 6
    0xa0c1, //  4: mov    isr, x
    0x8020, //  5: push   block
            //     .wrap
    0x2092, //  6: wait   1 gpio, 18
    0x0048, //  7: jmp    x--, 8
    0x2012, //  8: wait   0 gpio, 18
    0x0003, //  9: jmp    3
};

#if !PICO_NO_HARDWARE
static const struct pio_program pclk_count_program = {
    .instructions = pclk_count_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = pclk_count_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config pclk_count_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pclk_count_wrap_target, offset + pclk_count_wrap);
    return c;
}
#endif

// ---------- //
// href_count //
// ---------- //

#define href_count_wrap_target 1
#define href_count_wrap 3
#define href_count_pio_version 0

static const uint16_t href_count_program_instructions[] = {
    0xa02b, //  0: mov    x, ~null
            //     .wrap_target
    0x2091, //  1: wait   1 gpio, 17
    0x2011, //  2: wait   0 gpio, 17
    0x0041, //  3: jmp    x--, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program href_count_program = {
    .instructions = href_count_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = href_count_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x2
#endif
};

static inline pio_sm_config href_count_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + href_count_wrap_target, offset + href_count_wrap);
    return c;
}
#endif

// ---------------------------------------------------------------------------
// Hand-written init helpers (NOT generated by pioasm - pioasm only emits the
// program struct + get_default_config above). In_base must be a multiple of 8
// (GP8..GP15); in_shift autopush 8 gives one 8-bit pixel per RX FIFO entry;
// FIFO_JOIN_RX gives the 8-deep RX FIFO the DMA burst needs. Kept here to
// match the original hand-maintained camera.pio.h layout.
// ---------------------------------------------------------------------------
#if !PICO_NO_HARDWARE
static inline void capture_program_init(PIO pio, uint sm, uint offset, uint in_base) {
    pio_sm_config c = capture_program_get_default_config(offset);
    sm_config_set_in_pins(&c, in_base);              // GP8..GP15 (multiple of 8)
    sm_config_set_in_shift(&c, false, true, 8);      // shift left, autopush 8
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);   // 8-deep RX FIFO
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

static inline void capture_per_pclk_program_init(PIO pio, uint sm, uint offset, uint in_base) {
    pio_sm_config c = capture_per_pclk_program_get_default_config(offset);
    sm_config_set_in_pins(&c, in_base);
    sm_config_set_in_shift(&c, false, true, 8);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
#endif
